# Generated by Django 4.0.4 on 2023-01-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='bathroom',
            field=models.PositiveIntegerField(default=1, verbose_name='No bathroom'),
        ),
        migrations.AddField(
            model_name='estate',
            name='bedroom',
            field=models.PositiveIntegerField(default=1, verbose_name='No bedroom'),
        ),
        migrations.AddField(
            model_name='estate',
            name='toilet',
            field=models.PositiveIntegerField(default=1, verbose_name='No toilet'),
        ),
    ]
