# Generated by Django 4.0.4 on 2023-01-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_estate_bathroom_estate_bedroom_estate_toilet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
